version: '3'
services:
  db:
    image: mongo:6
    volumes: 
     - database:/data/db
    ports:
      - 27017:27017
  frontend:
    build:
      context: ./iitm-streamer-web
      dockerfile: Dockerfile
    ports:
      - 8080:80
  backend:
    build:
      context: ./iitm-streamer
      dockerfile: Dockerfile
    ports:
      - 4000:4000

volumes:
  database:
